/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchDelBtn: typeof import('./src/components/table-template/components/batch-del-btn.vue')['default']
    BtnGroup: typeof import('./src/components/btn-group/btn-group.vue')['default']
    CollapsePopoverBtn: typeof import('./src/components/collapse-popover-btn/collapse-popover-btn.vue')['default']
    ColumnsSettingBtn: typeof import('./src/components/table-template/components/columns-setting-btn.vue')['default']
    Components: typeof import('./src/components/table-template/components.vue')['default']
    DelBtn: typeof import('./src/components/popconfirm-btn/del-btn.vue')['default']
    Dialog: typeof import('./src/components/dialog/dialog.vue')['default']
    DndProvider: typeof import('./src/components/dnd-provider/dnd-provider.vue')['default']
    EditDelBtnGroup: typeof import('./src/components/table-template/components/edit-del-btn-group.vue')['default']
    EditorBtn: typeof import('./src/components/table-template/components/editor-btn.vue')['default']
    EditorDelBtnGroup: typeof import('./src/components/table-template/components/editor-del-btn-group.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialog: typeof import('naive-ui')['NDialog']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    PopconfirmBtn: typeof import('./src/components/popconfirm-btn/popconfirm-btn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableTemplate: typeof import('./src/components/table-template/table-template.vue')['default']
    TableTemplateFilter: typeof import('./src/components/table-template/components/table-template-filter.vue')['default']
    TableTemplateOperator: typeof import('./src/components/table-template/components/table-template-operator.vue')['default']
  }
}
